export const _UPDATE_VIEWPORT_DIMENSIONS_ = 'UPDATE_VIEWPORT_DIMENSIONS',
_GET_OS_INFO_ = 'GET_OS_INFO',
_GET_ENGINE_INFO_ = 'GET_ENGINE_INFO',
_GET_MOBILE_INFO_ = 'GET_MOBILE_INFO',
_GET_BROWSER_INFO_ = 'GET_BROWSER_INFO'